services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ai_telegram_bot
    environment:
      - PYTHONUNBUFFERED=1
    env_file: .env
    depends_on:
      pg:
        condition: service_healthy
    networks:
      - app-network


networks:
  app-network:
