name: Auto Approve Dependency PRs

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check if PR has 'dependencies' label
        id: check-label
        run: |
          echo "::set-output name=has-label::$(echo ${{ github.event.pull_request.labels }} | grep -c 'dependencies')"

      - name: Auto-approve PR
        if: steps.check-label.outputs.has-label != '0'
        uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto approved automated PR"
