name: auto approve deps with label 'dependencies'

on:
  pull_request:
    types:
      - labeled

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.label.name == 'dependencies'
    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto approved automated PR"
