name: lint and test
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - uses: pdm-project/setup-pdm@v4
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            .venv
      - name: Install dependencies
        run: pdm install -G dev
      - name: Run tests
        run: pdm run pytest
