name: lint and test
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - uses: pdm-project/setup-pdm@v4
      - name: Cache pdm packages
        uses: actions/cache@v4
        with:
          key: dotvenv-packege
          path: |
            .venv
      - name: Install dependencies
        run: pdm install -G dev
      - name: Run tests
        run: pdm run pytest
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - uses: pdm-project/setup-pdm@v4
      - name: Cache pdm packages
        uses: actions/cache@v4
        with:
          key: dotvenv-packege
          path: |
            .venv
      - name: Install dependencies
        run: pdm install -G dev

