name: lint and test
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install PDM
        run: python -m pip install --upgrade pip && pip install pdm
      - name: Install dependencies
        run: pdm install --dev
      - name: Run tests
        run: pdm run pytest
